// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.baidu.bjf.remoting.protobuf.v3.complexmap;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.bjf.remoting.protobuf.v3.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType&gt; phoneTypeEnumValueMap = 2;</code>
     */
    java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType>
    getPhoneTypeEnumValueMap();

    /**
     * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber&gt; phoneNumberObjectValueMap = 3;</code>
     */
    java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber>
    getPhoneNumberObjectValueMap();
  }
  /**
   * Protobuf type {@code com.baidu.bjf.remoting.protobuf.v3.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.baidu.bjf.remoting.protobuf.v3.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                phoneTypeEnumValueMap_ = com.google.protobuf.MapField.newMapField(
                    phoneTypeEnumValueMapDefaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.ByteString bytes = input.readBytes();
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              phoneTypeEnumValueMap = phoneTypeEnumValueMapDefaultEntry.getParserForType().parseFrom(bytes);
              if (com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.valueOf(phoneTypeEnumValueMap.getValue()) == null) {
                unknownFields.mergeLengthDelimitedField(2, bytes);
              } else {
                phoneTypeEnumValueMap_.getMutableMap().put(phoneTypeEnumValueMap.getKey(), phoneTypeEnumValueMap.getValue());
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                phoneNumberObjectValueMap_ = com.google.protobuf.MapField.newMapField(
                    phoneNumberObjectValueMapDefaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber>
              phoneNumberObjectValueMap = input.readMessage(
                  phoneNumberObjectValueMapDefaultEntry.getParserForType(), extensionRegistry);
              phoneNumberObjectValueMap_.getMutableMap().put(phoneNumberObjectValueMap.getKey(), phoneNumberObjectValueMap.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return phoneTypeEnumValueMap_;
        case 3:
          return phoneNumberObjectValueMap_;
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.class, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.Builder.class);
    }

    public static final com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2, 2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();
      /**
       * <code>required string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
       */
      boolean hasType();
      /**
       * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
       */
      com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType getType();
    }
    /**
     * Protobuf type {@code com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber}
     */
    public  static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber)
        PhoneNumberOrBuilder {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private PhoneNumber() {
        number_ = "";
        type_ = 1;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                number_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType value = com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = rawValue;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.class, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.Builder.class);
      }

      public static final com.google.protobuf.Parser<PhoneNumber> PARSER =
          new com.google.protobuf.AbstractParser<PhoneNumber>() {
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.Object number_;
      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
       */
      public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType getType() {
        com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType result = com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.valueOf(type_);
        return result == null ? com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.HOME : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber)
          com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.class, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.Builder.class);
        }

        // Construct using com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 1;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_descriptor;
        }

        public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber getDefaultInstanceForType() {
          return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.getDefaultInstance();
        }

        public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber build() {
          com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber buildPartial() {
          com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber result = new com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber) {
            return mergeFrom((com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber other) {
          if (other == com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            bitField0_ |= 0x00000001;
            number_ = other.number_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object number_ = "";
        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string number = 1;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              number_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }

        private int type_ = 1;
        /**
         * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType getType() {
          com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType result = com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.valueOf(type_);
          return result == null ? com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.HOME : result;
        }
        /**
         * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder setType(com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = 1;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber)
      private static final com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber defaultInstance;static {
        defaultInstance = new com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber();
      }

      public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }

      public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONETYPEENUMVALUEMAP_FIELD_NUMBER = 2;
    private static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> phoneTypeEnumValueMapDefaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneTypeEnumValueMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.ENUM,
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.MOBILE.getNumber());
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> phoneTypeEnumValueMap_ =
            com.google.protobuf.MapField.emptyMapField(
                phoneTypeEnumValueMapDefaultEntry);

    private static final
    com.google.protobuf.Internal.MapAdapter.Converter<
        java.lang.Integer, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType> phoneTypeEnumValueMapValueConverter =
            com.google.protobuf.Internal.MapAdapter.newEnumConverter(
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.internalGetValueMap(),
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType.MOBILE);
    /**
     * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType&gt; phoneTypeEnumValueMap = 2;</code>
     */

    public java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType>
    getPhoneTypeEnumValueMap() {
      return new com.google.protobuf.Internal.MapAdapter<
          java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType, java.lang.Integer>(
              phoneTypeEnumValueMap_.getMap(), phoneTypeEnumValueMapValueConverter);
    }

    public static final int PHONENUMBEROBJECTVALUEMAP_FIELD_NUMBER = 3;
    private static final com.google.protobuf.MapEntry<
        java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> phoneNumberObjectValueMapDefaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber>newDefaultInstance(
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumberObjectValueMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber.getDefaultInstance());
    private com.google.protobuf.MapField<
        java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> phoneNumberObjectValueMap_ =
            com.google.protobuf.MapField.emptyMapField(
                phoneNumberObjectValueMapDefaultEntry);

    /**
     * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber&gt; phoneNumberObjectValueMap = 3;</code>
     */

    public java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> getPhoneNumberObjectValueMap() {
      return phoneNumberObjectValueMap_.getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber item : getPhoneNumberObjectValueMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : phoneTypeEnumValueMap_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        phoneTypeEnumValueMap = phoneTypeEnumValueMapDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, phoneTypeEnumValueMap);
      }
      for (java.util.Map.Entry<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> entry
           : phoneNumberObjectValueMap_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber>
        phoneNumberObjectValueMap = phoneNumberObjectValueMapDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, phoneNumberObjectValueMap);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : phoneTypeEnumValueMap_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        phoneTypeEnumValueMap = phoneTypeEnumValueMapDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, phoneTypeEnumValueMap);
      }
      for (java.util.Map.Entry<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> entry
           : phoneNumberObjectValueMap_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber>
        phoneNumberObjectValueMap = phoneNumberObjectValueMapDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, phoneNumberObjectValueMap);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.bjf.remoting.protobuf.v3.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.bjf.remoting.protobuf.v3.Person)
        com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return phoneTypeEnumValueMap_;
          case 3:
            return phoneNumberObjectValueMap_;
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.class, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.Builder.class);
      }

      // Construct using com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneTypeEnumValueMap_.clear();
        phoneNumberObjectValueMap_.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor;
      }

      public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person getDefaultInstanceForType() {
        return com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.getDefaultInstance();
      }

      public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person build() {
        com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person buildPartial() {
        com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person result = new com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.phoneTypeEnumValueMap_ = phoneTypeEnumValueMap_.copy();
        result.phoneNumberObjectValueMap_ = phoneNumberObjectValueMap_.copy();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person) {
          return mergeFrom((com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person other) {
        if (other == com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        phoneTypeEnumValueMap_.mergeFrom(other.phoneTypeEnumValueMap_);
        phoneNumberObjectValueMap_.mergeFrom(other.phoneNumberObjectValueMap_);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber item : getPhoneNumberObjectValueMap().values()) {
          if (!item.isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> phoneTypeEnumValueMap_ =
              com.google.protobuf.MapField.newMapField(
                  phoneTypeEnumValueMapDefaultEntry);

      /**
       * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType&gt; phoneTypeEnumValueMap = 2;</code>
       */

      public java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType>
      getPhoneTypeEnumValueMap() {
        return new com.google.protobuf.Internal.MapAdapter<
            java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType, java.lang.Integer>(
                phoneTypeEnumValueMap_.getMap(), phoneTypeEnumValueMapValueConverter);
      }
      /**
       * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneType&gt; phoneTypeEnumValueMap = 2;</code>
       */

      public java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType>
      getMutablePhoneTypeEnumValueMap() {
        onChanged();
        return new com.google.protobuf.Internal.MapAdapter<
            java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneType, java.lang.Integer>(
                phoneTypeEnumValueMap_.getMutableMap(), phoneTypeEnumValueMapValueConverter);
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> phoneNumberObjectValueMap_ =
              com.google.protobuf.MapField.newMapField(
                  phoneNumberObjectValueMapDefaultEntry);

      /**
       * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber&gt; phoneNumberObjectValueMap = 3;</code>
       */
      public java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber> getPhoneNumberObjectValueMap() {
        return phoneNumberObjectValueMap_.getMap();
      }
      /**
       * <code>map&lt;string, .com.baidu.bjf.remoting.protobuf.v3.Person.PhoneNumber&gt; phoneNumberObjectValueMap = 3;</code>
       */
      public java.util.Map<java.lang.String, com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person.PhoneNumber>
      getMutablePhoneNumberObjectValueMap() {
        onChanged();
        return phoneNumberObjectValueMap_.getMutableMap();
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.bjf.remoting.protobuf.v3.Person)
    }

    // @@protoc_insertion_point(class_scope:com.baidu.bjf.remoting.protobuf.v3.Person)
    private static final com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person defaultInstance;static {
      defaultInstance = new com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person();
    }

    public static com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person getDefaultInstance() {
      return defaultInstance;
    }

    public com.baidu.bjf.remoting.protobuf.v3.complexmap.AddressBookProtos.Person getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneTypeEnumValueMapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneTypeEnumValueMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumberObjectValueMapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumberObjectValueMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\"com.baidu.bjf.remot" +
      "ing.protobuf.v3\"\356\004\n\006Person\022\014\n\004name\030\001 \002(\t" +
      "\022d\n\025phoneTypeEnumValueMap\030\002 \003(\0132E.com.ba" +
      "idu.bjf.remoting.protobuf.v3.Person.Phon" +
      "eTypeEnumValueMapEntry\022l\n\031phoneNumberObj" +
      "ectValueMap\030\003 \003(\0132I.com.baidu.bjf.remoti" +
      "ng.protobuf.v3.Person.PhoneNumberObjectV" +
      "alueMapEntry\032r\n\032PhoneTypeEnumValueMapEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022C\n\005value\030\002 \001(\01624.com.bai" +
      "du.bjf.remoting.protobuf.v3.Person.Phone",
      "Type:\0028\001\032x\n\036PhoneNumberObjectValueMapEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022E\n\005value\030\002 \001(\01326.com.bai" +
      "du.bjf.remoting.protobuf.v3.Person.Phone" +
      "Number:\0028\001\032g\n\013PhoneNumber\022\016\n\006number\030\001 \002(" +
      "\t\022H\n\004type\030\002 \001(\01624.com.baidu.bjf.remoting" +
      ".protobuf.v3.Person.PhoneType:\004HOME\"+\n\tP" +
      "honeType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002" +
      "BB\n-com.baidu.bjf.remoting.protobuf.v3.c" +
      "omplexmapB\021AddressBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor,
        new java.lang.String[] { "Name", "PhoneTypeEnumValueMap", "PhoneNumberObjectValueMap", });
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneTypeEnumValueMapEntry_descriptor =
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneTypeEnumValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneTypeEnumValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumberObjectValueMapEntry_descriptor =
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor.getNestedTypes().get(1);
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumberObjectValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumberObjectValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_descriptor =
      internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_descriptor.getNestedTypes().get(2);
    internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_bjf_remoting_protobuf_v3_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
