// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alltypes.proto

package com.baidu.bjf.remoting.protobuf;

public final class RequrieMessageType {
  private RequrieMessageType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InterClassNameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double doubleF = 1;
    /**
     * <code>optional double doubleF = 1;</code>
     */
    boolean hasDoubleF();
    /**
     * <code>optional double doubleF = 1;</code>
     */
    double getDoubleF();

    // repeated .pkg.InterClassName.CountryInfo type = 2;
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    java.util.List<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo> 
        getTypeList();
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo getType(int index);
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    int getTypeCount();
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    java.util.List<? extends com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder> 
        getTypeOrBuilderList();
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder getTypeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pkg.InterClassName}
   */
  public static final class InterClassName extends
      com.google.protobuf.GeneratedMessage
      implements InterClassNameOrBuilder {
    // Use InterClassName.newBuilder() to construct.
    private InterClassName(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InterClassName(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InterClassName defaultInstance;
    public static InterClassName getDefaultInstance() {
      return defaultInstance;
    }

    public InterClassName getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InterClassName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              doubleF_ = input.readDouble();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                type_ = new java.util.ArrayList<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              type_.add(input.readMessage(com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.class, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.Builder.class);
    }

    public static com.google.protobuf.Parser<InterClassName> PARSER =
        new com.google.protobuf.AbstractParser<InterClassName>() {
      public InterClassName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InterClassName(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InterClassName> getParserForType() {
      return PARSER;
    }

    public interface CountryInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required string code = 2;
      /**
       * <code>required string code = 2;</code>
       */
      boolean hasCode();
      /**
       * <code>required string code = 2;</code>
       */
      java.lang.String getCode();
      /**
       * <code>required string code = 2;</code>
       */
      com.google.protobuf.ByteString
          getCodeBytes();

      // optional int32 number = 3;
      /**
       * <code>optional int32 number = 3;</code>
       */
      boolean hasNumber();
      /**
       * <code>optional int32 number = 3;</code>
       */
      int getNumber();
    }
    /**
     * Protobuf type {@code pkg.InterClassName.CountryInfo}
     */
    public static final class CountryInfo extends
        com.google.protobuf.GeneratedMessage
        implements CountryInfoOrBuilder {
      // Use CountryInfo.newBuilder() to construct.
      private CountryInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CountryInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CountryInfo defaultInstance;
      public static CountryInfo getDefaultInstance() {
        return defaultInstance;
      }

      public CountryInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CountryInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                code_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                number_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_CountryInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_CountryInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.class, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<CountryInfo> PARSER =
          new com.google.protobuf.AbstractParser<CountryInfo>() {
        public CountryInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CountryInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CountryInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string code = 2;
      public static final int CODE_FIELD_NUMBER = 2;
      private java.lang.Object code_;
      /**
       * <code>required string code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 number = 3;
      public static final int NUMBER_FIELD_NUMBER = 3;
      private int number_;
      /**
       * <code>optional int32 number = 3;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 number = 3;</code>
       */
      public int getNumber() {
        return number_;
      }

      private void initFields() {
        name_ = "";
        code_ = "";
        number_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, number_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, number_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pkg.InterClassName.CountryInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_CountryInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_CountryInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.class, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder.class);
        }

        // Construct using com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          code_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          number_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_CountryInfo_descriptor;
        }

        public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo getDefaultInstanceForType() {
          return com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.getDefaultInstance();
        }

        public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo build() {
          com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo buildPartial() {
          com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo result = new com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.code_ = code_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.number_ = number_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo) {
            return mergeFrom((com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo other) {
          if (other == com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasCode()) {
            bitField0_ |= 0x00000002;
            code_ = other.code_;
            onChanged();
          }
          if (other.hasNumber()) {
            setNumber(other.getNumber());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasCode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required string code = 2;
        private java.lang.Object code_ = "";
        /**
         * <code>required string code = 2;</code>
         */
        public boolean hasCode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string code = 2;</code>
         */
        public java.lang.String getCode() {
          java.lang.Object ref = code_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            code_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string code = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCodeBytes() {
          java.lang.Object ref = code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string code = 2;</code>
         */
        public Builder setCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string code = 2;</code>
         */
        public Builder clearCode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          code_ = getDefaultInstance().getCode();
          onChanged();
          return this;
        }
        /**
         * <code>required string code = 2;</code>
         */
        public Builder setCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          code_ = value;
          onChanged();
          return this;
        }

        // optional int32 number = 3;
        private int number_ ;
        /**
         * <code>optional int32 number = 3;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 number = 3;</code>
         */
        public int getNumber() {
          return number_;
        }
        /**
         * <code>optional int32 number = 3;</code>
         */
        public Builder setNumber(int value) {
          bitField0_ |= 0x00000004;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 number = 3;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000004);
          number_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:pkg.InterClassName.CountryInfo)
      }

      static {
        defaultInstance = new CountryInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:pkg.InterClassName.CountryInfo)
    }

    private int bitField0_;
    // optional double doubleF = 1;
    public static final int DOUBLEF_FIELD_NUMBER = 1;
    private double doubleF_;
    /**
     * <code>optional double doubleF = 1;</code>
     */
    public boolean hasDoubleF() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double doubleF = 1;</code>
     */
    public double getDoubleF() {
      return doubleF_;
    }

    // repeated .pkg.InterClassName.CountryInfo type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private java.util.List<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo> type_;
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    public java.util.List<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo> getTypeList() {
      return type_;
    }
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    public java.util.List<? extends com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder> 
        getTypeOrBuilderList() {
      return type_;
    }
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo getType(int index) {
      return type_.get(index);
    }
    /**
     * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
     */
    public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder getTypeOrBuilder(
        int index) {
      return type_.get(index);
    }

    private void initFields() {
      doubleF_ = 0D;
      type_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getTypeCount(); i++) {
        if (!getType(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, doubleF_);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeMessage(2, type_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, doubleF_);
      }
      for (int i = 0; i < type_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, type_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pkg.InterClassName}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.class, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.Builder.class);
      }

      // Construct using com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTypeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        doubleF_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (typeBuilder_ == null) {
          type_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          typeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.bjf.remoting.protobuf.RequrieMessageType.internal_static_pkg_InterClassName_descriptor;
      }

      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName getDefaultInstanceForType() {
        return com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.getDefaultInstance();
      }

      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName build() {
        com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName buildPartial() {
        com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName result = new com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.doubleF_ = doubleF_;
        if (typeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            type_ = java.util.Collections.unmodifiableList(type_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName) {
          return mergeFrom((com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName other) {
        if (other == com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.getDefaultInstance()) return this;
        if (other.hasDoubleF()) {
          setDoubleF(other.getDoubleF());
        }
        if (typeBuilder_ == null) {
          if (!other.type_.isEmpty()) {
            if (type_.isEmpty()) {
              type_ = other.type_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTypeIsMutable();
              type_.addAll(other.type_);
            }
            onChanged();
          }
        } else {
          if (!other.type_.isEmpty()) {
            if (typeBuilder_.isEmpty()) {
              typeBuilder_.dispose();
              typeBuilder_ = null;
              type_ = other.type_;
              bitField0_ = (bitField0_ & ~0x00000002);
              typeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTypeFieldBuilder() : null;
            } else {
              typeBuilder_.addAllMessages(other.type_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTypeCount(); i++) {
          if (!getType(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double doubleF = 1;
      private double doubleF_ ;
      /**
       * <code>optional double doubleF = 1;</code>
       */
      public boolean hasDoubleF() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double doubleF = 1;</code>
       */
      public double getDoubleF() {
        return doubleF_;
      }
      /**
       * <code>optional double doubleF = 1;</code>
       */
      public Builder setDoubleF(double value) {
        bitField0_ |= 0x00000001;
        doubleF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleF = 1;</code>
       */
      public Builder clearDoubleF() {
        bitField0_ = (bitField0_ & ~0x00000001);
        doubleF_ = 0D;
        onChanged();
        return this;
      }

      // repeated .pkg.InterClassName.CountryInfo type = 2;
      private java.util.List<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          type_ = new java.util.ArrayList<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo>(type_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder> typeBuilder_;

      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public java.util.List<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo> getTypeList() {
        if (typeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(type_);
        } else {
          return typeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public int getTypeCount() {
        if (typeBuilder_ == null) {
          return type_.size();
        } else {
          return typeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo getType(int index) {
        if (typeBuilder_ == null) {
          return type_.get(index);
        } else {
          return typeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder setType(
          int index, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.set(index, value);
          onChanged();
        } else {
          typeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder setType(
          int index, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.set(index, builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder addType(com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.add(value);
          onChanged();
        } else {
          typeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder addType(
          int index, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.add(index, value);
          onChanged();
        } else {
          typeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder addType(
          com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.add(builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder addType(
          int index, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.add(index, builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo> values) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          super.addAll(values, type_);
          onChanged();
        } else {
          typeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          typeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public Builder removeType(int index) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.remove(index);
          onChanged();
        } else {
          typeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder getTypeBuilder(
          int index) {
        return getTypeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder getTypeOrBuilder(
          int index) {
        if (typeBuilder_ == null) {
          return type_.get(index);  } else {
          return typeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public java.util.List<? extends com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder> 
           getTypeOrBuilderList() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(type_);
        }
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder addTypeBuilder() {
        return getTypeFieldBuilder().addBuilder(
            com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder addTypeBuilder(
          int index) {
        return getTypeFieldBuilder().addBuilder(
            index, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .pkg.InterClassName.CountryInfo type = 2;</code>
       */
      public java.util.List<com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder> 
           getTypeBuilderList() {
        return getTypeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder> 
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfo.Builder, com.baidu.bjf.remoting.protobuf.RequrieMessageType.InterClassName.CountryInfoOrBuilder>(
                  type_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pkg.InterClassName)
    }

    static {
      defaultInstance = new InterClassName(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pkg.InterClassName)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pkg_InterClassName_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pkg_InterClassName_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pkg_InterClassName_CountryInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pkg_InterClassName_CountryInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016alltypes.proto\022\003pkg\"\213\001\n\016InterClassName" +
      "\022\017\n\007doubleF\030\001 \001(\001\022-\n\004type\030\002 \003(\0132\037.pkg.In" +
      "terClassName.CountryInfo\0329\n\013CountryInfo\022" +
      "\014\n\004name\030\001 \002(\t\022\014\n\004code\030\002 \002(\t\022\016\n\006number\030\003 " +
      "\001(\005B5\n\037com.baidu.bjf.remoting.protobufB\022" +
      "RequrieMessageType"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pkg_InterClassName_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pkg_InterClassName_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pkg_InterClassName_descriptor,
              new java.lang.String[] { "DoubleF", "Type", });
          internal_static_pkg_InterClassName_CountryInfo_descriptor =
            internal_static_pkg_InterClassName_descriptor.getNestedTypes().get(0);
          internal_static_pkg_InterClassName_CountryInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pkg_InterClassName_CountryInfo_descriptor,
              new java.lang.String[] { "Name", "Code", "Number", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
