// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.baidu.jprotobuf.pbrpc.meta;

public final class RpcServiceMetaListPojoClass {
  private RpcServiceMetaListPojoClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcServiceMetaListPojoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    java.util.List<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo> 
        getRpcServiceMetasList();
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo getRpcServiceMetas(int index);
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    int getRpcServiceMetasCount();
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    java.util.List<? extends com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder> 
        getRpcServiceMetasOrBuilderList();
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder getRpcServiceMetasOrBuilder(
        int index);

    // repeated int32 val = 2;
    /**
     * <code>repeated int32 val = 2;</code>
     */
    java.util.List<java.lang.Integer> getValList();
    /**
     * <code>repeated int32 val = 2;</code>
     */
    int getValCount();
    /**
     * <code>repeated int32 val = 2;</code>
     */
    int getVal(int index);
  }
  /**
   * Protobuf type {@code com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojo}
   */
  public static final class RpcServiceMetaListPojo extends
      com.google.protobuf.GeneratedMessage
      implements RpcServiceMetaListPojoOrBuilder {
    // Use RpcServiceMetaListPojo.newBuilder() to construct.
    private RpcServiceMetaListPojo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcServiceMetaListPojo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcServiceMetaListPojo defaultInstance;
    public static RpcServiceMetaListPojo getDefaultInstance() {
      return defaultInstance;
    }

    public RpcServiceMetaListPojo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcServiceMetaListPojo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rpcServiceMetas_ = new java.util.ArrayList<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo>();
                mutable_bitField0_ |= 0x00000001;
              }
              rpcServiceMetas_.add(input.readMessage(com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                val_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              val_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                val_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                val_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rpcServiceMetas_ = java.util.Collections.unmodifiableList(rpcServiceMetas_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          val_ = java.util.Collections.unmodifiableList(val_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.class, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcServiceMetaListPojo> PARSER =
        new com.google.protobuf.AbstractParser<RpcServiceMetaListPojo>() {
      public RpcServiceMetaListPojo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcServiceMetaListPojo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcServiceMetaListPojo> getParserForType() {
      return PARSER;
    }

    // repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;
    public static final int RPCSERVICEMETAS_FIELD_NUMBER = 1;
    private java.util.List<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo> rpcServiceMetas_;
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    public java.util.List<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo> getRpcServiceMetasList() {
      return rpcServiceMetas_;
    }
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    public java.util.List<? extends com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder> 
        getRpcServiceMetasOrBuilderList() {
      return rpcServiceMetas_;
    }
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    public int getRpcServiceMetasCount() {
      return rpcServiceMetas_.size();
    }
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo getRpcServiceMetas(int index) {
      return rpcServiceMetas_.get(index);
    }
    /**
     * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
     */
    public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder getRpcServiceMetasOrBuilder(
        int index) {
      return rpcServiceMetas_.get(index);
    }

    // repeated int32 val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> val_;
    /**
     * <code>repeated int32 val = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getValList() {
      return val_;
    }
    /**
     * <code>repeated int32 val = 2;</code>
     */
    public int getValCount() {
      return val_.size();
    }
    /**
     * <code>repeated int32 val = 2;</code>
     */
    public int getVal(int index) {
      return val_.get(index);
    }

    private void initFields() {
      rpcServiceMetas_ = java.util.Collections.emptyList();
      val_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rpcServiceMetas_.size(); i++) {
        output.writeMessage(1, rpcServiceMetas_.get(i));
      }
      for (int i = 0; i < val_.size(); i++) {
        output.writeInt32(2, val_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rpcServiceMetas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rpcServiceMetas_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < val_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(val_.get(i));
        }
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.class, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.Builder.class);
      }

      // Construct using com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRpcServiceMetasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rpcServiceMetasBuilder_ == null) {
          rpcServiceMetas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rpcServiceMetasBuilder_.clear();
        }
        val_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_descriptor;
      }

      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo getDefaultInstanceForType() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.getDefaultInstance();
      }

      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo build() {
        com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo buildPartial() {
        com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo result = new com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo(this);
        int from_bitField0_ = bitField0_;
        if (rpcServiceMetasBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rpcServiceMetas_ = java.util.Collections.unmodifiableList(rpcServiceMetas_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rpcServiceMetas_ = rpcServiceMetas_;
        } else {
          result.rpcServiceMetas_ = rpcServiceMetasBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          val_ = java.util.Collections.unmodifiableList(val_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.val_ = val_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo) {
          return mergeFrom((com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo other) {
        if (other == com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo.getDefaultInstance()) return this;
        if (rpcServiceMetasBuilder_ == null) {
          if (!other.rpcServiceMetas_.isEmpty()) {
            if (rpcServiceMetas_.isEmpty()) {
              rpcServiceMetas_ = other.rpcServiceMetas_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRpcServiceMetasIsMutable();
              rpcServiceMetas_.addAll(other.rpcServiceMetas_);
            }
            onChanged();
          }
        } else {
          if (!other.rpcServiceMetas_.isEmpty()) {
            if (rpcServiceMetasBuilder_.isEmpty()) {
              rpcServiceMetasBuilder_.dispose();
              rpcServiceMetasBuilder_ = null;
              rpcServiceMetas_ = other.rpcServiceMetas_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rpcServiceMetasBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRpcServiceMetasFieldBuilder() : null;
            } else {
              rpcServiceMetasBuilder_.addAllMessages(other.rpcServiceMetas_);
            }
          }
        }
        if (!other.val_.isEmpty()) {
          if (val_.isEmpty()) {
            val_ = other.val_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValIsMutable();
            val_.addAll(other.val_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaListPojo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;
      private java.util.List<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo> rpcServiceMetas_ =
        java.util.Collections.emptyList();
      private void ensureRpcServiceMetasIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rpcServiceMetas_ = new java.util.ArrayList<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo>(rpcServiceMetas_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder> rpcServiceMetasBuilder_;

      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public java.util.List<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo> getRpcServiceMetasList() {
        if (rpcServiceMetasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rpcServiceMetas_);
        } else {
          return rpcServiceMetasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public int getRpcServiceMetasCount() {
        if (rpcServiceMetasBuilder_ == null) {
          return rpcServiceMetas_.size();
        } else {
          return rpcServiceMetasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo getRpcServiceMetas(int index) {
        if (rpcServiceMetasBuilder_ == null) {
          return rpcServiceMetas_.get(index);
        } else {
          return rpcServiceMetasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder setRpcServiceMetas(
          int index, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo value) {
        if (rpcServiceMetasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.set(index, value);
          onChanged();
        } else {
          rpcServiceMetasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder setRpcServiceMetas(
          int index, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder builderForValue) {
        if (rpcServiceMetasBuilder_ == null) {
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.set(index, builderForValue.build());
          onChanged();
        } else {
          rpcServiceMetasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder addRpcServiceMetas(com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo value) {
        if (rpcServiceMetasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.add(value);
          onChanged();
        } else {
          rpcServiceMetasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder addRpcServiceMetas(
          int index, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo value) {
        if (rpcServiceMetasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.add(index, value);
          onChanged();
        } else {
          rpcServiceMetasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder addRpcServiceMetas(
          com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder builderForValue) {
        if (rpcServiceMetasBuilder_ == null) {
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.add(builderForValue.build());
          onChanged();
        } else {
          rpcServiceMetasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder addRpcServiceMetas(
          int index, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder builderForValue) {
        if (rpcServiceMetasBuilder_ == null) {
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.add(index, builderForValue.build());
          onChanged();
        } else {
          rpcServiceMetasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder addAllRpcServiceMetas(
          java.lang.Iterable<? extends com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo> values) {
        if (rpcServiceMetasBuilder_ == null) {
          ensureRpcServiceMetasIsMutable();
          super.addAll(values, rpcServiceMetas_);
          onChanged();
        } else {
          rpcServiceMetasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder clearRpcServiceMetas() {
        if (rpcServiceMetasBuilder_ == null) {
          rpcServiceMetas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rpcServiceMetasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public Builder removeRpcServiceMetas(int index) {
        if (rpcServiceMetasBuilder_ == null) {
          ensureRpcServiceMetasIsMutable();
          rpcServiceMetas_.remove(index);
          onChanged();
        } else {
          rpcServiceMetasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder getRpcServiceMetasBuilder(
          int index) {
        return getRpcServiceMetasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder getRpcServiceMetasOrBuilder(
          int index) {
        if (rpcServiceMetasBuilder_ == null) {
          return rpcServiceMetas_.get(index);  } else {
          return rpcServiceMetasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public java.util.List<? extends com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder> 
           getRpcServiceMetasOrBuilderList() {
        if (rpcServiceMetasBuilder_ != null) {
          return rpcServiceMetasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rpcServiceMetas_);
        }
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder addRpcServiceMetasBuilder() {
        return getRpcServiceMetasFieldBuilder().addBuilder(
            com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder addRpcServiceMetasBuilder(
          int index) {
        return getRpcServiceMetasFieldBuilder().addBuilder(
            index, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo rpcServiceMetas = 1;</code>
       */
      public java.util.List<com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder> 
           getRpcServiceMetasBuilderList() {
        return getRpcServiceMetasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder> 
          getRpcServiceMetasFieldBuilder() {
        if (rpcServiceMetasBuilder_ == null) {
          rpcServiceMetasBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder>(
                  rpcServiceMetas_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rpcServiceMetas_ = null;
        }
        return rpcServiceMetasBuilder_;
      }

      // repeated int32 val = 2;
      private java.util.List<java.lang.Integer> val_ = java.util.Collections.emptyList();
      private void ensureValIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          val_ = new java.util.ArrayList<java.lang.Integer>(val_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getValList() {
        return java.util.Collections.unmodifiableList(val_);
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public int getValCount() {
        return val_.size();
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public int getVal(int index) {
        return val_.get(index);
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public Builder setVal(
          int index, int value) {
        ensureValIsMutable();
        val_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public Builder addVal(int value) {
        ensureValIsMutable();
        val_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureValIsMutable();
        super.addAll(values, val_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 val = 2;</code>
       */
      public Builder clearVal() {
        val_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojo)
    }

    static {
      defaultInstance = new RpcServiceMetaListPojo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojo)
  }

  public interface RpcServiceMetaPojoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string serviceName = 1;
    /**
     * <code>optional string serviceName = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>optional string serviceName = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>optional string serviceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    // optional string methodName = 2;
    /**
     * <code>optional string methodName = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>optional string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>optional string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    // optional string inputProto = 3;
    /**
     * <code>optional string inputProto = 3;</code>
     */
    boolean hasInputProto();
    /**
     * <code>optional string inputProto = 3;</code>
     */
    java.lang.String getInputProto();
    /**
     * <code>optional string inputProto = 3;</code>
     */
    com.google.protobuf.ByteString
        getInputProtoBytes();

    // optional string outputProto = 4;
    /**
     * <code>optional string outputProto = 4;</code>
     */
    boolean hasOutputProto();
    /**
     * <code>optional string outputProto = 4;</code>
     */
    java.lang.String getOutputProto();
    /**
     * <code>optional string outputProto = 4;</code>
     */
    com.google.protobuf.ByteString
        getOutputProtoBytes();
  }
  /**
   * Protobuf type {@code com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo}
   */
  public static final class RpcServiceMetaPojo extends
      com.google.protobuf.GeneratedMessage
      implements RpcServiceMetaPojoOrBuilder {
    // Use RpcServiceMetaPojo.newBuilder() to construct.
    private RpcServiceMetaPojo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcServiceMetaPojo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcServiceMetaPojo defaultInstance;
    public static RpcServiceMetaPojo getDefaultInstance() {
      return defaultInstance;
    }

    public RpcServiceMetaPojo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcServiceMetaPojo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              inputProto_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              outputProto_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.class, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcServiceMetaPojo> PARSER =
        new com.google.protobuf.AbstractParser<RpcServiceMetaPojo>() {
      public RpcServiceMetaPojo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcServiceMetaPojo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcServiceMetaPojo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string serviceName = 1;
    public static final int SERVICENAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string methodName = 2;
    public static final int METHODNAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    /**
     * <code>optional string methodName = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string methodName = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string inputProto = 3;
    public static final int INPUTPROTO_FIELD_NUMBER = 3;
    private java.lang.Object inputProto_;
    /**
     * <code>optional string inputProto = 3;</code>
     */
    public boolean hasInputProto() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string inputProto = 3;</code>
     */
    public java.lang.String getInputProto() {
      java.lang.Object ref = inputProto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          inputProto_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string inputProto = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInputProtoBytes() {
      java.lang.Object ref = inputProto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputProto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string outputProto = 4;
    public static final int OUTPUTPROTO_FIELD_NUMBER = 4;
    private java.lang.Object outputProto_;
    /**
     * <code>optional string outputProto = 4;</code>
     */
    public boolean hasOutputProto() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string outputProto = 4;</code>
     */
    public java.lang.String getOutputProto() {
      java.lang.Object ref = outputProto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          outputProto_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string outputProto = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOutputProtoBytes() {
      java.lang.Object ref = outputProto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputProto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceName_ = "";
      methodName_ = "";
      inputProto_ = "";
      outputProto_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getInputProtoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getOutputProtoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getInputProtoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getOutputProtoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.class, com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.Builder.class);
      }

      // Construct using com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        inputProto_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        outputProto_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_descriptor;
      }

      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo getDefaultInstanceForType() {
        return com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.getDefaultInstance();
      }

      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo build() {
        com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo buildPartial() {
        com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo result = new com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.inputProto_ = inputProto_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.outputProto_ = outputProto_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo) {
          return mergeFrom((com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo other) {
        if (other == com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasInputProto()) {
          bitField0_ |= 0x00000004;
          inputProto_ = other.inputProto_;
          onChanged();
        }
        if (other.hasOutputProto()) {
          bitField0_ |= 0x00000008;
          outputProto_ = other.outputProto_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaListPojoClass.RpcServiceMetaPojo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string serviceName = 1;
      private java.lang.Object serviceName_ = "";
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      // optional string methodName = 2;
      private java.lang.Object methodName_ = "";
      /**
       * <code>optional string methodName = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      // optional string inputProto = 3;
      private java.lang.Object inputProto_ = "";
      /**
       * <code>optional string inputProto = 3;</code>
       */
      public boolean hasInputProto() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string inputProto = 3;</code>
       */
      public java.lang.String getInputProto() {
        java.lang.Object ref = inputProto_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          inputProto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string inputProto = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInputProtoBytes() {
        java.lang.Object ref = inputProto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inputProto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string inputProto = 3;</code>
       */
      public Builder setInputProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        inputProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string inputProto = 3;</code>
       */
      public Builder clearInputProto() {
        bitField0_ = (bitField0_ & ~0x00000004);
        inputProto_ = getDefaultInstance().getInputProto();
        onChanged();
        return this;
      }
      /**
       * <code>optional string inputProto = 3;</code>
       */
      public Builder setInputProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        inputProto_ = value;
        onChanged();
        return this;
      }

      // optional string outputProto = 4;
      private java.lang.Object outputProto_ = "";
      /**
       * <code>optional string outputProto = 4;</code>
       */
      public boolean hasOutputProto() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string outputProto = 4;</code>
       */
      public java.lang.String getOutputProto() {
        java.lang.Object ref = outputProto_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          outputProto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string outputProto = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOutputProtoBytes() {
        java.lang.Object ref = outputProto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outputProto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string outputProto = 4;</code>
       */
      public Builder setOutputProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        outputProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string outputProto = 4;</code>
       */
      public Builder clearOutputProto() {
        bitField0_ = (bitField0_ & ~0x00000008);
        outputProto_ = getDefaultInstance().getOutputProto();
        onChanged();
        return this;
      }
      /**
       * <code>optional string outputProto = 4;</code>
       */
      public Builder setOutputProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        outputProto_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo)
    }

    static {
      defaultInstance = new RpcServiceMetaPojo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.jprotobuf.pbrpc.meta.RpcServiceMetaPojo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmeta.proto\022\036com.baidu.jprotobuf.pbrpc." +
      "meta\"r\n\026RpcServiceMetaListPojo\022K\n\017rpcSer" +
      "viceMetas\030\001 \003(\01322.com.baidu.jprotobuf.pb" +
      "rpc.meta.RpcServiceMetaPojo\022\013\n\003val\030\002 \003(\005" +
      "\"f\n\022RpcServiceMetaPojo\022\023\n\013serviceName\030\001 " +
      "\001(\t\022\022\n\nmethodName\030\002 \001(\t\022\022\n\ninputProto\030\003 " +
      "\001(\t\022\023\n\013outputProto\030\004 \001(\tB\035B\033RpcServiceMe" +
      "taListPojoClass"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaListPojo_descriptor,
              new java.lang.String[] { "RpcServiceMetas", "Val", });
          internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_jprotobuf_pbrpc_meta_RpcServiceMetaPojo_descriptor,
              new java.lang.String[] { "ServiceName", "MethodName", "InputProto", "OutputProto", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
